
execute pathogen#infect()

filetype plugin indent on
syntax on

set noswapfile
filetype plugin indent on
" On pressing tab, insert 2 spaces
set expandtab
" show existing tab with 2 spaces width
set tabstop=2
set softtabstop=2
" when indenting with '>', use 2 spaces width
set shiftwidth=2
set mouse=a

call plug#begin()

" List your plugins here
Plug 'tpope/vim-sensible'
Plug 'airblade/vim-gitgutter'
" Plug 'urbit/hoon.vim'

call plug#end()
