#!/usr/bin/env zsh

alias hogs='k top po -A |sort -k4 -h'
alias cogs='k top po -A |sort -k3 -h'
alias drain='~/zsh_functions/k8s-drain.sh'

alias node-util='kubectl get nodes --no-headers | awk '\''{print $1}'\'' | xargs -I {} sh -c '\''echo {} ; kubectl describe node {} | grep Allocated -A 5 | grep -ve Event -ve Allocated -ve percent -ve -- ; echo '\'''
alias pod-reqs='kubectl get po -o custom-columns="Name:metadata.name,CPU-request:spec.containers[*].resources.requests.cpu"'
alias pod-leqs='kubectl get po -o custom-columns="Name:metadata.name,CPU-limit:spec.containers[*].resources.limits.cpu"'
alias mod-reqs='kubectl get po -o custom-columns="Name:metadata.name,Memory-request:spec.containers[*].resources.requests.memory"'
alias mod-leqs='kubectl get po -o custom-columns="Name:metadata.name,Memory-limit:spec.containers[*].resources.limits.memory"'

alias kn='kubens'
alias kx='kubectx'
alias ketall='kubectl get-all'
alias kev='kubectl everything'

source $HOME/zsh_functions/whatswrong

alias whatswrong='wrong_in_all_ns'
alias lwhatswrong='watch '"'"'zsh -c "source '$HOME'/zsh_functions/whatswrong; wrong_in_all_ns"'"'"''
alias lnwhatswrong='watch '"'"'zsh -c "source '$HOME'/zsh_functions/whatswrong; wrong_in_ns"'"'"''
alias nwhatswrong="wrong_in_ns"
alias dnwhatswrong="for i (\$(wrong_namespaces)); do \
  kubens \$i; \
    wrong_pods_in_ns|xargs kubectl delete po --wait=false; \
  done"
alias dwhatswrong="wrong_pods_in_ns|xargs kubectl delete po"

source $HOME/zsh_functions/completed
alias completed='completed_in_all_ns'
alias delcomplete="for i (\$(completed_namespaces)); do \
  kubens \$i; \
    completed_in_ns|xargs kubectl delete po; \
  done"

source $HOME/zsh_functions/linstorps

alias grc='git rebase --continue'
alias ga='git add'
alias gap='git add -p'
alias gc='git commit -v -s'
alias gcm='git commit -v -s -m'
alias gmf='git merge --ff-only'
alias gd='git diff'
alias gdc='git diff --cached'
alias gl='git l'
alias gs='git status'
alias gsl='git stash list -u'
alias gsd='git stash drop'

alias be='bundle exec'
alias k=kubectl
alias kg='kubectl get -A'
alias ks='kubectl -n kube-system'
alias kcss='kubectl -n cozy-system'
alias kcf='kubectl -n cozy-fluxcd'
alias kls='kubectl -n cozy-linstor'
alias kff='kubectl --namespace=flux-system'
alias fa='flux get ks -A|egrep -v ^flux-system'
alias faa='flux get ks -A'
alias fak='flux get ks'
# alias supertldr="pushd /Users/yebyen/projects/weaveworks/kubeconfig-ca-fetch && make clean && make supertldr && popd"

alias gtd='git tag -d'
alias gpo='git push origin'
alias gp='git push'
alias moo='ssh moo'
alias msi='ssh msi'
alias qgit='git'

do-gh-get-authtoken () {
#  ~/go/bin/yq r ~/.config/gh/hosts.yml '"github.com".oauth_token'
#  ~/go/bin/yq '."github.com".oauth_token' ~/.config/gh/hosts.yml
  gh config get -h github.com oauth_token
}

alias ghtoken='export GITHUB_TOKEN=`do-gh-get-authtoken`'
